### ISSUE TITLE
GMsummon doesn’t add _C

### ISSUE THREAD

**Issue by DeadCanadian** [DrPennysworth/ArkSpawnCodeGen#1]
Gmsummon codes should have _C at the end of the creatures ID but don’t appear to causing the codes to not function

**Comment by DrPennysworth** [comment]
> Gmsummon codes should have _C at the end of the creatures ID but don’t appear to causing the codes to not function

I made this years ago my man I'm not maintaining it. Its only up because someone asked me for my code so I used github to let him use my code. I'm honestly surprised any of it still works. I wrote this when I was brand new to coding haha.

Also IF people really show interest id be willing to remake this code in a DLL for people to use.
